### ISSUE TITLE
Probability of winning player should be displayed two digits after decimal currently it is displaying 14 digits after decimal

### ISSUE THREAD

**Issue by Agrawal-Deepti** [konglingwengit/SSW695_Ping-Pong_King#66]
1. Open https://ping-pong-king-666.uc.r.appspot.com/a.html
2. Enter  player in both player dropdown text boxes
3. Click on Predict button - Note that Probability value shows 14 digits after decimal it should display only two digits after decimal

![image](https://user-images.githubusercontent.com/78319350/140182009-0eedcad3-5f62-4c00-ab95-1144d626d037.png)

**Comment by LightenJ** [comment]
Removed because probability of win is no longer part of the prediction
