### ISSUE TITLE
On 125% display resolution  selecting two players and clicking on predict button changing the location of "Money Line" text box

### ISSUE THREAD

**Issue by Agrawal-Deepti** [konglingwengit/SSW695_Ping-Pong_King#67]
Open https://ping-pong-king-666.uc.r.appspot.com/a.html
Enter player in both player dropdown text boxes
Click on Predict button - Note that clicking on predict button changing the location of Money line text box it should not change text box location it should be fixed

![image](https://user-images.githubusercontent.com/78319350/140183006-db064f14-5f41-4c4d-ba60-f4dcf696ee3b.png)

**Comment by LightenJ** [comment]
![image](https://user-images.githubusercontent.com/55630543/142731606-d517c784-daf5-4725-b409-09932625128e.png)

Money line is removed, and 125% resolution appears to be working correctly now.  See image above; I tried a fair bit of resizing without seeing a box jump this way.
