### ISSUE TITLE
On Statistics page both player list should be display side by side for the consistency with predict tab and  clicking on player statistics should display information of that particular player and match statistics button should be displayed below player list

### ISSUE THREAD

**Issue by Agrawal-Deepti** [konglingwengit/SSW695_Ping-Pong_King#75]
1. Login to pingpongking website
2. Go to Statistics page - Note that both player list displayed one below other instead it should be displayed side by side so that it will be consistent with predict tab
3. Player statistics button should be added for both player list and it should be displayed player info only for that particular player  
4. and then Match statistics button should be displayed in the center and it should be match both the displayed player and display match info only if matching statics between both the players is available else it should produce message that there is no matching between both the players 

![image](https://user-images.githubusercontent.com/78319350/141369435-390d38d1-720b-47e1-814d-537f9c5dc93c.png)

**Comment by LightenJ** [comment]
Marking this as complete, since Lingwen and Bin made the player statistics page pretty.  We can write a new one if we need to, but I'm pretty sure we don't want to revert their changes and make it look like the prediction page.
