### ISSUE TITLE
Statistics report should be displayed in tabular format 

### ISSUE THREAD

**Issue by Agrawal-Deepti** [konglingwengit/SSW695_Ping-Pong_King#80]
1. Login to pingpong king website
2. select player 1 and 2 and try to fetch player statistics - IT will show results in blocks instead it should be displayed in tabular format which will look neat and clean to understand statistics to the end user.
 
![image](https://user-images.githubusercontent.com/78319350/142063008-adbe1152-062f-4403-9437-8bbad5f0f814.png)

**Comment by LightenJ** [comment]
Lingwen and Bin fixed this; I'm closing it for them to keep our issues up to date.
