### ISSUE TITLE
Statistics: Add borders to the table, Column names should be bold, Match statistics row labels should be left aligned and table should be displayed in the center of the page

### ISSUE THREAD

**Issue by Agrawal-Deepti** [konglingwengit/SSW695_Ping-Pong_King#81]
1. Login to pingpong king website
2. Select two players and click on match statistics button - It gives new table but its good to add border to the table, column names should be make it bold and match statistics row labels should be left aligned and display table in the center to look it better as a output
   
![image](https://user-images.githubusercontent.com/78319350/142345196-e46547cd-25ff-43bc-99eb-4be3beb05219.png)

**Comment by LightenJ** [comment]
Marking complete based on everyone approving Bin/Lingwen's new design.
